name: hi-my-friends
# events, push event: jobs run every time someone pushes a change to the repository
on: [push]  
# jobs groups
jobs:
  # job name
  to-greet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1.1.0
        with:
          repo-token: secrets.GITHUB_TOKEN
          issue-message: Hi, nice to see u here!
          pr-message: Hi, nice to see u here!
